import { StudentProfile, ResumeData, RoadmapData, JobListing, CandidateApplication, PricingPlan, DailyQuest, Badge, Hackathon, Certification } from '../types';

export const initialStudentProfile: StudentProfile = {
  id: 'stu-101',
  name: 'Alex Chen',
  email: 'alex.chen@university.edu',
  university: 'Stanford University / IIT Delhi Exchange',
  major: 'Computer Science & Artificial Intelligence',
  graduationYear: 2026,
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  xp: 14250,
  coins: 450,
  level: 12,
  streakDays: 18,
  placementScore: 92,
  bio: 'Building AI-first developer tools and full-stack web applications. Passionate about distributed systems, vector databases, and high-performance frontend interfaces.',
  skills: ['TypeScript', 'React 19', 'Next.js', 'Express', 'Python', 'Gemini API', 'PostgreSQL', 'Docker', 'Redis', 'TailwindCSS'],
  badges: [
    { id: 'b1', title: 'Top 1% Resume Score', icon: '🏆', description: 'Scored 90+ on AI ATS Analysis', category: 'code', earnedAt: '2026-07-20' },
    { id: 'b2', title: '14-Day Coding Streak', icon: '🔥', description: 'Consistently coded and completed quests for 14 days', category: 'streak', earnedAt: '2026-08-01' },
    { id: 'b3', title: 'System Architecture Pro', icon: '⚡', description: 'Passed Mock System Design Interview with 95% Clarity', category: 'interview', earnedAt: '2026-08-04' },
    { id: 'b4', title: 'Hackathon Champion', icon: '🥇', description: '1st Place in Global AI Hackathon 2026', category: 'community', earnedAt: '2026-06-15' },
  ],
  links: {
    github: 'https://github.com/alexchen-dev',
    linkedin: 'https://linkedin.com/in/alexchen-ai',
    portfolio: 'https://alexchen.dev',
  },
};

export const initialDailyQuests: DailyQuest[] = [
  { id: 'q1', title: 'Analyze Resume with AI Scanner', xpReward: 150, progress: 100, completed: true, category: 'resume' },
  { id: 'q2', title: 'Complete 1 AI Technical Interview Session', xpReward: 250, progress: 50, completed: false, category: 'interview' },
  { id: 'q3', title: 'Generate & Share 1 Technical Post on LinkedIn', xpReward: 200, progress: 0, completed: false, category: 'networking' },
  { id: 'q4', title: 'Review 2 Skill Gap Recommendations', xpReward: 100, progress: 100, completed: true, category: 'code' },
];

export const sampleResume: ResumeData = {
  personalInfo: {
    fullName: 'Alex Chen',
    email: 'alex.chen@university.edu',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA / New Delhi',
    website: 'https://alexchen.dev',
    github: 'https://github.com/alexchen-dev',
    linkedin: 'https://linkedin.com/in/alexchen-ai',
    summary: 'Full Stack AI Engineer and Senior CS student building high-concurrency cloud services and reactive frontend design systems. Proven experience with React, TypeScript, Express, PostgreSQL, and Google GenAI APIs.',
  },
  education: [
    {
      id: 'e1',
      school: 'Stanford University',
      degree: 'Bachelor of Science',
      fieldOfStudy: 'Computer Science (AI & Systems Track)',
      startDate: 'Sep 2022',
      endDate: 'Jun 2026',
      gpa: '3.92 / 4.0',
    },
  ],
  experience: [
    {
      id: 'x1',
      title: 'Full Stack AI Engineering Intern',
      company: 'Vercel / Linear Partner Studio',
      location: 'San Francisco, CA (Remote)',
      startDate: 'May 2025',
      endDate: 'Aug 2025',
      current: false,
      bullets: [
        'Architected a real-time collaborative code review extension used by 12,000+ active developer sessions.',
        'Engineered Express middleware with Redis caching layer, reducing API latency from 240ms to 42ms under 5k QPS load.',
        'Integrated Gemini Flash 3.6 streaming API for instant AI automated pull-request summaries.',
      ],
    },
    {
      id: 'x2',
      title: 'Software Development Intern',
      company: 'Stripe Ecosystem Accelerator',
      location: 'Remote',
      startDate: 'Jan 2025',
      endDate: 'Apr 2025',
      current: false,
      bullets: [
        'Built automated merchant onboarding workflows using React, TypeScript, and TailwindCSS v4.',
        'Developed end-to-end webhook integration test suites with Jest and Playwright, improving test coverage to 96%.',
      ],
    },
  ],
  projects: [
    {
      id: 'p1',
      name: 'Navricon Platform Monorepo',
      description: 'Unified career ecosystem platform with automated resume scanner, audio/video interview studio, and candidate recruiter matching.',
      techStack: ['React 19', 'TypeScript', 'Express', 'Navricon API', 'PostgreSQL', 'TailwindCSS'],
      link: 'https://github.com/alexchen-dev/navricon-platform',
      bullets: [
        'Integrated Gemini 3.6 Flash and Gemini TTS for real-time AI interview audio voice synthesis.',
        'Engineered responsive Glassmorphic design system supporting smooth Framer Motion transitions.',
      ],
    },
    {
      id: 'p2',
      name: 'RAG Document Intelligence Service',
      description: 'Vector search engine processing multi-page SEC filing PDFs using Qdrant vector database and embeddings.',
      techStack: ['Python', 'FastAPI', 'Qdrant', 'LangChain', 'Docker'],
      link: 'https://github.com/alexchen-dev/rag-doc-engine',
      bullets: [
        'Implemented semantic chunking algorithms and hybrid vector-keyword retrieval with 94.2% precision.',
      ],
    },
  ],
  skills: {
    languages: ['TypeScript', 'JavaScript', 'Python', 'SQL', 'C++', 'HTML/CSS'],
    frameworks: ['React 19', 'Next.js', 'Express', 'FastAPI', 'TailwindCSS', 'Zustand', 'Motion'],
    databases: ['PostgreSQL', 'Redis', 'Qdrant', 'Prisma ORM'],
    tools: ['Git', 'Docker', 'Google Cloud Run', 'GitHub Actions', 'Vite', 'VS Code'],
  },
};

export const sampleJobListings: JobListing[] = [
  {
    id: 'job-1',
    title: 'Founding Full Stack Engineer (AI Platform)',
    company: 'Linear Ecosystem / YC W26',
    logo: '⚡',
    location: 'San Francisco, CA / Remote',
    type: 'Internship',
    stipend: '$8,000 - $11,000 / month',
    tags: ['React 19', 'TypeScript', 'Node.js', 'Gemini API', 'PostgreSQL'],
    matchScore: 96,
    applicantsCount: 42,
    postedDate: '2 hours ago',
    description: 'Looking for an ambitious engineering student to build real-time collaborative workspace tools with modern AI agent integration.',
    requirements: [
      'Strong proficiency in TypeScript, React, and Node.js backend architecture',
      'Experience building with LLM APIs (Gemini, OpenAI, Claude)',
      'Eye for pristine UI design and micro-interactions',
    ],
    status: 'applied',
  },
  {
    id: 'job-2',
    title: 'AI Systems & RAG Engineer Intern',
    company: 'Anthropic Partner Studio',
    logo: '🧠',
    location: 'New York, NY / Hybrid',
    type: 'Internship',
    stipend: '$9,500 / month',
    tags: ['Python', 'FastAPI', 'VectorDB', 'Embeddings', 'LangChain'],
    matchScore: 91,
    applicantsCount: 88,
    postedDate: '1 day ago',
    description: 'Work alongside senior researchers to build production vector search pipelines and evaluation frameworks for high-speed LLM agents.',
    requirements: [
      'Deep understanding of Python, async programming, and vector search indexing',
      'Familiarity with embeddings, chunking strategies, and hybrid retrieval',
    ],
    status: 'interviewing',
  },
  {
    id: 'job-3',
    title: 'Frontend Architecture Engineer',
    company: 'Vercel Ecosystem',
    logo: '▲',
    location: 'Remote',
    type: 'Full-time',
    stipend: '$140,000 - $175,000 / year + Equity',
    tags: ['React', 'Next.js', 'TailwindCSS', 'WebSockets', 'Canvas'],
    matchScore: 88,
    applicantsCount: 120,
    postedDate: '3 days ago',
    description: 'Join our core platform design system team building lightning-fast interactive dashboards and developer tooling.',
    requirements: [
      'Mastery of modern CSS, Tailwind, DOM performance, and WebSockets',
      'Experience creating published open-source npm packages or design systems',
    ],
  },
  {
    id: 'job-4',
    title: 'Backend Systems & Cloud Engineer',
    company: 'Stripe Accelerator',
    logo: '💳',
    location: 'Austin, TX / Remote',
    type: 'Internship',
    stipend: '$7,500 / month',
    tags: ['Express', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    matchScore: 85,
    applicantsCount: 64,
    postedDate: '4 days ago',
    description: 'Help scale our global payment processing microservices handling high-concurrency webhook streams.',
    requirements: [
      'Experience with SQL database indexing and query optimization',
      'Knowledge of Redis caching patterns and background worker queues',
    ],
  },
];

export const sampleCandidateApplications: CandidateApplication[] = [
  {
    id: 'app-101',
    candidateName: 'Alex Chen',
    university: 'Stanford University',
    major: 'Computer Science & AI',
    gradYear: 2026,
    matchScore: 96,
    appliedRole: 'Founding Full Stack Engineer',
    stage: 'Technical Round',
    appliedDate: '2026-08-01',
    skills: ['React 19', 'Express', 'Gemini API', 'PostgreSQL', 'Docker'],
    resumeUrl: '#',
    aiNotes: 'Top candidate. Scored 96% in AI code architecture match. Excellent STAR response in system design.',
  },
  {
    id: 'app-102',
    candidateName: 'Priya Sharma',
    university: 'IIT Bombay',
    major: 'Data Science & ML',
    gradYear: 2026,
    matchScore: 93,
    appliedRole: 'AI Systems Engineer Intern',
    stage: 'Screening',
    appliedDate: '2026-08-03',
    skills: ['Python', 'FastAPI', 'Qdrant', 'PyTorch', 'LangChain'],
    resumeUrl: '#',
    aiNotes: 'Strong research background. Built an open-source vector search benchmark with 500+ GitHub stars.',
  },
  {
    id: 'app-103',
    candidateName: 'Marcus Vance',
    university: 'UC Berkeley',
    major: 'EECS',
    gradYear: 2025,
    matchScore: 89,
    appliedRole: 'Frontend Architecture Engineer',
    stage: 'Culture Fit',
    appliedDate: '2026-07-28',
    skills: ['React', 'Next.js', 'TailwindCSS', 'Framer Motion'],
    resumeUrl: '#',
    aiNotes: 'Exceptional visual polish. Created custom canvas animation libraries.',
  },
  {
    id: 'app-104',
    candidateName: 'Sophia Lin',
    university: 'MIT',
    major: 'Computer Science',
    gradYear: 2026,
    matchScore: 94,
    appliedRole: 'Founding Full Stack Engineer',
    stage: 'Offered',
    appliedDate: '2026-07-25',
    skills: ['Node.js', 'PostgreSQL', 'Redis', 'TypeScript', 'GraphQL'],
    resumeUrl: '#',
    aiNotes: 'Offered position. Completed take-home system design in record time.',
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: 'plan-student-free',
    name: 'Student Starter',
    priceMonthly: 0,
    priceAnnual: 0,
    description: 'Essential AI career tools for first-year and sophomore college students.',
    targetUser: 'student',
    ctaText: 'Start Free Today',
    features: [
      '3 AI Resume Scans per month',
      'Basic AI Career Roadmap generator',
      '1 Mock Technical Interview / week',
      'Access to Internship Directory',
      'Basic Community Badges & XP',
    ],
  },
  {
    id: 'plan-student-pro',
    name: 'Student Pro (Placement Pass)',
    priceMonthly: 19,
    priceAnnual: 14,
    popular: true,
    description: 'Unlimited AI power to supercharge placements, portfolios, and top startup offers.',
    targetUser: 'student',
    ctaText: 'Upgrade to Pro Pass',
    features: [
      'Unlimited AI Resume Scans & Section Rewrites',
      'Unlimited AI Voice Mock Interviews + Audio Feedback',
      'Personalized Skill Gap Radar & Salary Benchmarks',
      'LinkedIn Viral Content & Networking Outreach AI',
      '1-Click One-Page Portfolio Website Generator',
      'Verified Skill Credential Badge for Recruiters',
    ],
  },
  {
    id: 'plan-startup',
    name: 'Startup Recruit Scale',
    priceMonthly: 149,
    priceAnnual: 119,
    popular: true,
    description: 'Automated AI sourcing, screening, and candidate matching for high-growth tech teams.',
    targetUser: 'company',
    ctaText: 'Start Sourcing Talent',
    features: [
      'AI Candidate Sourcing & Automated Ranking Engine',
      'Up to 10 Active Job / Internship Postings',
      'Automated AI Voice & Text Applicant Screening',
      'Candidate Pipeline Kanban & Stage Tracking',
      '1-Click Personalized Recruiter Outreach Messages',
      'Direct College Placement Cell Verification',
    ],
  },
  {
    id: 'plan-university',
    name: 'University Enterprise',
    priceMonthly: 499,
    priceAnnual: 399,
    description: 'Comprehensive placement cell operating system for universities & colleges.',
    targetUser: 'college',
    ctaText: 'Schedule Demo & Onboard',
    features: [
      'Full Student Placement Cell Analytics Dashboard',
      'Department-level Skill Gap Heatmaps & Batch Reports',
      'Automated Verified Student Credential Issuance',
      'Company Campus Recruitment Management Portal',
      'Dedicated Customer Success & AI Custom Fine-tuning',
      'SLA & Enterprise SSO Authentication',
    ],
  },
];

export const upcomingHackathons: Hackathon[] = [
  {
    id: 'hack-1',
    title: 'AWS GenAI Builder Clash 2026',
    organizer: 'Amazon Web Services & DevPost',
    logo: '☁️',
    startDate: '2026-08-20',
    endDate: '2026-08-25',
    mode: 'Online',
    prizePool: '$50,000 USD',
    techStack: ['AWS Bedrock', 'Claude 3.5', 'Python', 'React', 'AWS Lambda'],
    description: 'Build production-ready generative AI agents using Amazon Bedrock, Titan, and Claude models. Top teams win direct interview passes for AWS AI Teams.',
    status: 'Registration Open',
    participantsCount: 3820,
    registrationUrl: 'https://aws.devpost.com/hackathons/genai-clash-2026',
    tracks: ['Healthcare AI', 'Developer Tooling', 'Financial Tech Agents'],
    featured: true,
  },
  {
    id: 'hack-2',
    title: 'Microsoft Azure AI & Cloud Innovation Summit',
    organizer: 'Microsoft Azure Ecosystem',
    logo: '🔷',
    startDate: '2026-09-01',
    endDate: '2026-09-05',
    mode: 'Hybrid',
    prizePool: '$40,000 USD',
    techStack: ['Azure OpenAI', 'Azure AI Search', 'TypeScript', 'CosmosDB', 'Docker'],
    description: 'Construct multi-modal AI enterprise apps using Azure Cognitive Services and Azure AI Studio. Includes free $500 Azure Cloud credits for registered participants.',
    status: 'Upcoming',
    participantsCount: 2150,
    registrationUrl: 'https://azure.microsoft.com/en-us/community/hackathons',
    tracks: ['Enterprise RAG Systems', 'Autonomous Agents', 'Green Tech Cloud'],
    featured: true,
  },
  {
    id: 'hack-3',
    title: 'NPTEL National Student TechSprint 2026',
    organizer: 'NPTEL & IIT Madras Placement Cell',
    logo: '🎓',
    startDate: '2026-08-15',
    endDate: '2026-08-18',
    mode: 'Online',
    prizePool: '₹10,000,000 INR',
    techStack: ['Python', 'Deep Learning', 'PyTorch', 'React', 'FastAPI'],
    description: 'India’s largest nationwide student hackathon for NPTEL certified learners. Build solutions for smart agriculture, healthcare, and rural cloud infrastructure.',
    status: 'Registration Open',
    participantsCount: 12400,
    registrationUrl: 'https://nptel.ac.in/techsprint2026',
    tracks: ['Smart Agriculture', 'EdTech AI', 'Cloud & Systems'],
    featured: true,
  },
  {
    id: 'hack-4',
    title: 'Smart India Hackathon (SIH 2026) - Senior Edition',
    organizer: 'Ministry of Education (Govt of India)',
    logo: '🇮🇳',
    startDate: '2026-09-20',
    endDate: '2026-09-22',
    mode: 'In-Person',
    prizePool: '₹1,500,000 / Problem Statement',
    techStack: ['Node.js', 'PostgreSQL', 'Python', 'React Native', 'Flutter'],
    description: 'World’s largest open innovation model solving real-world challenges posed by Central Ministries, State Governments, and Industry Leaders.',
    status: 'Upcoming',
    participantsCount: 45000,
    registrationUrl: 'https://sih.gov.in',
    tracks: ['Smart Communication', 'MedTech', 'Robotics & AI'],
  },
  {
    id: 'hack-5',
    title: 'Global AI Agent & Gemini Developer World Cup',
    organizer: 'Google Cloud & AI Studio',
    logo: '✨',
    startDate: '2026-08-28',
    endDate: '2026-09-02',
    mode: 'Online',
    prizePool: '$100,000 USD',
    techStack: ['Gemini 3.6 Flash', 'Google GenAI SDK', 'Express', 'React 19', 'TailwindCSS'],
    description: 'Create revolutionary web applications powered by Gemini models, Live Audio API, and Multimodal Antigravity Agents.',
    status: 'Registration Open',
    participantsCount: 8900,
    registrationUrl: 'https://ai.google.dev/competition',
    tracks: ['Generative Web Apps', 'Multimodal Assistant', 'Developer Automation'],
    featured: true,
  },
];

export const featuredCertifications: Certification[] = [
  // NPTEL Certifications
  {
    id: 'cert-nptel-1',
    title: 'Deep Learning & Neural Networks',
    provider: 'NPTEL',
    level: 'Elite + Gold',
    badgeUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    badgeIcon: '📜',
    category: 'Artificial Intelligence & ML',
    description: '12-Week Rigorous Course offered by IIT Madras. Covers backpropagation, CNNs, RNNs, Transformers, and PyTorch implementations.',
    skillsCovered: ['PyTorch', 'CNNs', 'Transformers', 'Backpropagation', 'Deep Learning'],
    examCode: 'NPTEL26CS88',
    recommendedPrepDays: 21,
    status: 'Completed',
    verificationUrl: 'https://nptel.ac.in/noc/Ecertificate/?q=NPTEL26CS88S123',
    score: '94% (Top 1% National Roll)',
    nptelCourseId: 'noc26-cs88',
    issueDate: '2026-05-15',
  },
  {
    id: 'cert-nptel-2',
    title: 'Cloud Computing & Microservices Architecture',
    provider: 'NPTEL',
    level: 'Elite + Gold',
    badgeUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=200&auto=format&fit=crop&q=80',
    badgeIcon: '☁️',
    category: 'Cloud Engineering',
    description: '8-Week Course by IIT Kharagpur. Focuses on virtualization, Docker containers, Kubernetes orchestration, OpenStack, and distributed storage.',
    skillsCovered: ['Docker', 'Kubernetes', 'Microservices', 'Distributed Storage', 'OpenStack'],
    examCode: 'NPTEL26CS45',
    recommendedPrepDays: 14,
    status: 'Completed',
    verificationUrl: 'https://nptel.ac.in/noc/Ecertificate/?q=NPTEL26CS45S456',
    score: '91% (Elite + Gold)',
    nptelCourseId: 'noc26-cs45',
    issueDate: '2026-04-10',
  },
  {
    id: 'cert-nptel-3',
    title: 'Data Structures and Algorithms using Python',
    provider: 'NPTEL',
    level: 'Elite + Gold',
    badgeUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=200&auto=format&fit=crop&q=80',
    badgeIcon: '🐍',
    category: 'Computer Science Fundamentals',
    description: 'Offered by Chennai Mathematical Institute / NPTEL. In-depth analysis of graph algorithms, dynamic programming, and asymptotic time complexity.',
    skillsCovered: ['Python', 'Data Structures', 'Dynamic Programming', 'Graph Theory', 'Algorithms'],
    examCode: 'NPTEL26CS12',
    recommendedPrepDays: 18,
    status: 'Completed',
    verificationUrl: 'https://nptel.ac.in/noc/Ecertificate/?q=NPTEL26CS12S789',
    score: '96% (National Topper)',
    nptelCourseId: 'noc26-cs12',
    issueDate: '2025-11-20',
  },

  // AWS Certifications
  {
    id: 'cert-aws-1',
    title: 'AWS Certified Solutions Architect – Associate',
    provider: 'AWS',
    level: 'Associate',
    badgeUrl: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=200&auto=format&fit=crop&q=80',
    badgeIcon: '🟧',
    category: 'Cloud Architecture & Infrastructure',
    description: 'Validates ability to design resilient, high-performing, secure, and cost-optimized architectures on Amazon Web Services.',
    skillsCovered: ['AWS EC2', 'S3', 'RDS', 'VPC', 'IAM', 'CloudFront', 'Lambda', 'AutoScaling'],
    examCode: 'SAA-C03',
    recommendedPrepDays: 30,
    status: 'Completed',
    verificationUrl: 'https://www.credly.com/badges/aws-solutions-architect-assoc-alexchen',
    score: '885 / 1000',
    issueDate: '2026-02-14',
  },
  {
    id: 'cert-aws-2',
    title: 'AWS Certified AI Practitioner',
    provider: 'AWS',
    level: 'Foundational',
    badgeUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    badgeIcon: '🤖',
    category: 'Artificial Intelligence & ML',
    description: 'Highlights overall understanding of AI, ML, and generative AI concepts and relevant AWS AI services like Amazon Bedrock, SageMaker, and Q.',
    skillsCovered: ['Amazon Bedrock', 'SageMaker', 'Generative AI', 'Prompt Engineering', 'LLM Security'],
    examCode: 'AIF-C01',
    recommendedPrepDays: 14,
    status: 'In Progress',
    verificationUrl: '',
    score: 'Target Exam Date: Sep 2026',
  },
  {
    id: 'cert-aws-3',
    title: 'AWS Certified Developer – Associate',
    provider: 'AWS',
    level: 'Associate',
    badgeUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=200&auto=format&fit=crop&q=80',
    badgeIcon: '⚡',
    category: 'DevOps & Serverless',
    description: 'Demonstrates proficiency in developing, deploying, and debugging cloud-based applications using AWS Serverless and CI/CD tools.',
    skillsCovered: ['AWS DynamoDB', 'API Gateway', 'AWS CDK', 'CloudWatch', 'SQS/SNS'],
    examCode: 'DVA-C02',
    recommendedPrepDays: 25,
    status: 'Explore',
  },

  // Azure Certifications
  {
    id: 'cert-azure-1',
    title: 'Microsoft Certified: Azure AI Engineer Associate',
    provider: 'Azure',
    level: 'Associate',
    badgeUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    badgeIcon: '🟦',
    category: 'Artificial Intelligence & Cognitive Services',
    description: 'Validates expertise in building, managing, and deploying AI solutions leveraging Azure OpenAI Services, Azure Cognitive Search, and Speech AI.',
    skillsCovered: ['Azure OpenAI', 'Azure Cognitive Search', 'Bot Framework', 'Azure AI Vision', 'RAG Architecture'],
    examCode: 'AI-102',
    recommendedPrepDays: 28,
    status: 'Completed',
    verificationUrl: 'https://learn.microsoft.com/en-us/users/alexchen/credentials/azure-ai-102',
    score: '910 / 1000',
    issueDate: '2026-06-01',
  },
  {
    id: 'cert-azure-2',
    title: 'Microsoft Certified: Azure Fundamentals',
    provider: 'Azure',
    level: 'Foundational',
    badgeUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=200&auto=format&fit=crop&q=80',
    badgeIcon: '🌐',
    category: 'Cloud Basics',
    description: 'Foundational knowledge of cloud services and how those services are provided with Microsoft Azure.',
    skillsCovered: ['Azure Architecture', 'Azure Governance', 'Identity & Security', 'Virtual Machines'],
    examCode: 'AZ-900',
    recommendedPrepDays: 10,
    status: 'Completed',
    verificationUrl: 'https://learn.microsoft.com/en-us/users/alexchen/credentials/azure-az-900',
    score: '940 / 1000',
    issueDate: '2025-09-18',
  },
  {
    id: 'cert-azure-3',
    title: 'Microsoft Certified: Azure Developer Associate',
    provider: 'Azure',
    level: 'Associate',
    badgeUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=200&auto=format&fit=crop&q=80',
    badgeIcon: '💻',
    category: 'Cloud Development',
    description: 'Designing, building, testing, and maintaining cloud applications and services on Microsoft Azure.',
    skillsCovered: ['Azure App Service', 'Azure Functions', 'Azure Key Vault', 'Event Grid'],
    examCode: 'AZ-204',
    recommendedPrepDays: 25,
    status: 'Explore',
  },
];

